export const BASE_WEAPON_IMAGES: Record<string, string> = {
  "Кровавая луна (S)": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W010_WS0000.png",
  "Плохая репутация": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W011_WS0000.png",
  "Бластер": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W028_WS0000.png",
  "Взрывной осколок": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W007_WS0000.png",
  "Поджигатель": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W034_WS0000.png",
  "Подавление": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W004_WS0000.png",
  "Безразличие": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W016_WS0000.png",
  "Панацея": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W014_WS0000.png",
  "Дисциплина": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W001_WS0000.png",
  "Лихорадка": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W002_WS0000.png",
  "Светлячок": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W029_WS0000.png",
  "Призрачный перец": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W008_WS0000.png",
  "Весёлая жизнь": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W013_WS0000.png",
  "Бешеный пёс (S)": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W005_WS0000.png",
  "Мясник": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W006_WS0000.png",
  "Первопроходец": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W009_WS0000.png",
  "Разрушитель": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W012_WS0000.png",
  "Дымовик": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W027_WS0000.png",
  "Злоба": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__W015_WS0000.png",
  "Вихререз": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin_S2__MW001_WS2083.png",
  "Рассекатель(топор)": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin__MW003_WS0000.png",
  "Молот": "https://raw.githubusercontent.com/RyusAceVA/fragpunk-assets/main/weapons/skins_icon/Icon_WeaponSkin_S2__MW004_WS0000.png"
};
