import { listPosts, savePost } from "@/db/content";
import { makeWeaponContent, type WeaponFields } from "@/lib/weapon-content";
import type { HubPost } from "@/lib/hub-content";

type WeaponSeed = { title: string; summary: string; description: string; fields: Partial<WeaponFields> };

const base = (fields: Partial<WeaponFields>): WeaponFields => ({
  image: "", video: "", lancers: [], range: "medium", style: "balanced", control: "medium", role: "universal",
  kind: "firearm", category: "pistols", fireMode: "automatic",
  damageRanges: ["0–15 м", "25–40 м", "40–60 м"], damageHead: ["", "", ""], damageBody: ["", "", ""], damageLimbs: ["", "", ""],
  magazine: "", reserveAmmo: "", equipTime: "", crouchSpeed: "", walkSpeed: "", runSpeed: "", fireRate: "", zoom: "", adsTime: "",
  meleeLightDamage: "", meleeLightBackstab: "", meleeHeavyDamage: "", meleeHeavyBackstab: "", meleeChargeDamage: "", meleeChargeBackstab: "", dashDistance: "", chargeTime: "", attackArea: "",
  description: "", ...fields,
});

const weapons: WeaponSeed[] = [
  { title: "Bad Moon-S", summary: "Полуавтоматическая марксманская винтовка для точных средних дистанций.", description: "Требует уверенных одиночных выстрелов и хорошей позиции.", fields: { category:"marksman-rifles", fireMode:"semi-automatic", range:"long", style:"careful", control:"medium", damageHead:["108","","96"], damageBody:["45","","40"], damageLimbs:["42","","38"], fireRate:"462 /мин", magazine:"15", reserveAmmo:"45" } },
  { title: "Bad Reputation", summary: "Тяжёлая полуавтоматическая марксманская винтовка с высоким уроном.", description: "Сильна в руках игрока, который уверенно попадает в голову.", fields: { category:"marksman-rifles", fireMode:"semi-automatic", range:"long", style:"careful", control:"hard", damageHead:["154","","132"], damageBody:["70","","60"], damageLimbs:["66","","57"], fireRate:"300 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "My Way", summary: "Ручной пулемёт с большим магазином и стабильным темпом огня.", description: "Подходит для удержания линии и поддержки команды.", fields: { category:"lmgs", fireMode:"automatic", range:"medium", style:"balanced", control:"medium", damageHead:["87","","80"], damageBody:["25","","23"], damageLimbs:["23","","21"], fireRate:"652 /мин", magazine:"45", reserveAmmo:"180" } },
  { title: "Ghost Pepper", summary: "Скорострельный ручной пулемёт для подавления и контроля проходов.", description: "Лучше всего раскрывается при подготовленной позиции.", fields: { category:"lmgs", fireMode:"automatic", range:"medium", style:"aggressive", control:"hard", damageHead:["98","","87"], damageBody:["28","","25"], damageLimbs:["26","","23"], fireRate:"600–800 /мин", magazine:"100", reserveAmmo:"300" } },
  { title: "Лихорадка", summary: "Универсальная штурмовая винтовка для средних дистанций.", description: "Надёжный выбор, если нужен понятный автомат под большинство ситуаций.", fields: { category:"assault-rifles", fireMode:"automatic", range:"medium", style:"balanced", control:"medium", damageRanges:["0–25 м","25–40 м","40–60 м"], damageHead:["101","92","84"], damageBody:["35","32","29"], damageLimbs:["33","30","27"], fireRate:"522 /мин", magazine:"30", reserveAmmo:"120" } },
  { title: "Discipline", summary: "Быстрая штурмовая винтовка для активной игры на средней дистанции.", description: "Темп огня помогает в разменах, но требует контроля очереди.", fields: { category:"assault-rifles", fireMode:"automatic", range:"medium", style:"aggressive", control:"medium", damageHead:["67","62","57"], damageBody:["25","23","23"], damageLimbs:["24","22","20"], fireRate:"682 /мин", magazine:"30", reserveAmmo:"120" } },
  { title: "Mad Dog-S", summary: "Пистолет-пулемёт для быстрого входа и ближних дуэлей.", description: "Сокращай дистанцию и не затягивай перестрелку на длинной линии.", fields: { category:"smgs", fireMode:"automatic", range:"close", style:"aggressive", control:"medium", damageHead:["39","36","33"], damageBody:["26","24","22"], damageLimbs:["22","20","18"], fireRate:"759 /мин", magazine:"25", reserveAmmo:"100" } },
  { title: "Clampdown", summary: "Очень скорострельный ПП для агрессивной игры вблизи.", description: "Максимально опасен на короткой дистанции; контролируй отдачу.", fields: { category:"smgs", fireMode:"automatic", range:"close", style:"aggressive", control:"hard", damageHead:["33","28","22"], damageBody:["22","19","15"], damageLimbs:["18","16","12"], fireRate:"1091 /мин", magazine:"25", reserveAmmo:"100" } },
  { title: "Boom Broom", summary: "Автоматический дробовик с восемью дробинами в выстреле.", description: "Используй узкие проходы и короткие углы.", fields: { category:"shotguns", fireMode:"automatic", range:"close", style:"aggressive", control:"easy", damageHead:["22×8","18×8","15×8"], damageBody:["15×8","12×8","10×8"], damageLimbs:["12×8","10×8","8×8"], fireRate:"222 /мин", magazine:"8", reserveAmmo:"24" } },
  { title: "Meat Maker", summary: "Мощный дробовик для точечных выстрелов в упор.", description: "Один из лучших вариантов для подготовленного ближнего контакта.", fields: { category:"shotguns", fireMode:"bolt", range:"close", style:"careful", control:"medium", damageHead:["25×11","18×11","15×11"], damageBody:["17×11","12×11","10×11"], damageLimbs:["12×11","11×11","10×11"], fireRate:"100 /мин", magazine:"8", reserveAmmo:"24" } },
  { title: "Highlife", summary: "Снайперская винтовка с высоким разовым уроном.", description: "Для дальних линий, терпеливого выбора позиции и аккуратного отхода.", fields: { category:"sniper-rifles", fireMode:"bolt", range:"long", style:"careful", control:"hard", damageHead:["300","240","200"], damageBody:["150","120","108"], damageLimbs:["135","108","90"], fireRate:"61 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "Resolver", summary: "Болтовая снайперская винтовка для решающего первого контакта.", description: "Выстрел должен давать преимущество команде, поэтому всегда держи путь отхода.", fields: { category:"sniper-rifles", fireMode:"bolt", range:"long", style:"careful", control:"hard", damageHead:["300","","200"], damageBody:["150","","130"], damageLimbs:["143","","123"], fireRate:"40 /мин", magazine:"5", reserveAmmo:"10" } },
  { title: "Burner", summary: "Утилитарное оружие с зажигательными боеприпасами.", description: "Используй для контроля зоны и вынуждения противника выйти из укрытия.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"support", control:"easy", damageHead:["60","","54"], damageBody:["20","","18"], damageLimbs:["17","","15"], fireRate:"600 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "Smoker", summary: "Утилитарное оружие с дымовыми боеприпасами.", description: "Помогает перекрывать обзор и безопаснее занимать пространство.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"support", control:"easy", damageHead:["60","","54"], damageBody:["20","","18"], damageLimbs:["17","","15"], fireRate:"600 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "Flasher", summary: "Утилитарное оружие со светошумовыми боеприпасами.", description: "Дай эффект перед выходом команды, а не после него.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"support", control:"easy", damageHead:["60","","54"], damageBody:["20","","18"], damageLimbs:["17","","15"], fireRate:"600 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "Blaster", summary: "Утилитарное оружие с мини-гранатами.", description: "Используй, чтобы выбить противника из сильной позиции.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"support", control:"easy", damageHead:["60","","54"], damageBody:["20","","18"], damageLimbs:["17","","15"], fireRate:"600 /мин", magazine:"10", reserveAmmo:"30" } },
  { title: "Cold Shoulder", summary: "Автоматический пистолет как надёжный запасной вариант.", description: "Хорошо подходит, когда основной магазин уже пуст и нужно закончить размен.", fields: { category:"pistols", fireMode:"automatic", range:"close", style:"balanced", control:"easy", damageHead:["46","","40"], damageBody:["23","","20"], damageLimbs:["19","","17"], fireRate:"600 /мин", magazine:"15", reserveAmmo:"60" } },
  { title: "Vicious", summary: "Точный полуавтоматический пистолет с высоким уроном.", description: "Награждает за спокойный темп и попадания в голову.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"careful", control:"medium", damageHead:["150","143","133"], damageBody:["73","70","65"], damageLimbs:["65","63","58"], fireRate:"250 /мин", magazine:"7", reserveAmmo:"35" } },
  { title: "Cure-All", summary: "Полуавтоматический пистолет с тремя пулями при стрельбе от бедра.", description: "Гибкий запасной вариант для короткой и средней дистанции.", fields: { category:"pistols", fireMode:"semi-automatic", range:"medium", style:"balanced", control:"medium", damageHead:["70","","64"], damageBody:["35","","32"], damageLimbs:["29","","27"], fireRate:"333 /мин", magazine:"18", reserveAmmo:"72" } },
  { title: "Standard Blitzer", summary: "Стандартный клинок с рывком при заряженной атаке.", description: "Заряженный удар опасен в упор; атака в спину получает множитель 2×.", fields: { kind:"melee", category:"melee", fireMode:"single", range:"close", style:"aggressive", control:"medium", meleeLightDamage:"50", meleeHeavyDamage:"75", meleeChargeDamage:"100–150", meleeLightBackstab:"100", meleeHeavyBackstab:"150", meleeChargeBackstab:"200–300" } },
  { title: "Standard Striker", summary: "Стандартный клинок с увеличенной дистанцией атаки.", description: "Имеет больше досягаемости, чем Blitzer; атака в спину получает множитель 2×.", fields: { kind:"melee", category:"melee", fireMode:"single", range:"close", style:"aggressive", control:"medium", meleeLightDamage:"60", meleeHeavyDamage:"80", meleeChargeDamage:"100–150", meleeLightBackstab:"120", meleeHeavyBackstab:"160", meleeChargeBackstab:"200–300" } },
];

export async function seedWeaponCatalog(): Promise<{ created: number; skipped: number }> {
  const existing = new Set((await listPosts(true)).map((post) => post.title.trim().toLocaleLowerCase("ru-RU")));
  let created = 0;
  for (let index = 0; index < weapons.length; index += 1) {
    const weapon = weapons[index];
    if (existing.has(weapon.title.toLocaleLowerCase("ru-RU"))) continue;
    const content = makeWeaponContent(base({ ...weapon.fields, description: weapon.description }));
    await savePost({ type:"weapon", title:weapon.title, summary:weapon.summary, content, readTime:"2 мин", accent:index % 3 === 0 ? "acid" : index % 3 === 1 ? "purple" : "cyan", published:true, sortOrder:1000 + index }, "site-owner");
    created += 1;
  }
  return { created, skipped: weapons.length - created };
}
